apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smart-restaurant-prod

resources:
  - ../../base

images:
  - name: smart-restaurant
    newName: smart-restaurant
    newTag: "latest"

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: smart-restaurant