apiVersion: v1
kind: Service
metadata:
  name: smart-restaurant-svc
  labels:
    app: smart-restaurant
spec:
  selector:
    app: smart-restaurant
  ports:
    - name: websocket
      port: 8080
      targetPort: 8080
      protocol: TCP
  # ClusterIP: chỉ truy cập nội bộ cluster.
  # Đổi thành LoadBalancer nếu muốn expose ra ngoài trực tiếp.
  type: ClusterIP
